# -*- coding: utf-8 -*-
"""Machine_failure_detector_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQdimBb3uG01A09RQmlGe9qTSGYD_3RG
"""

!pip install streamlit
!pip install onnxruntime

import streamlit as st
import numpy as np
import onnxruntime as rt

# Load ONNX models
dt_sess = rt.InferenceSession("/content/decision_tree.onnx")
lr_sess = rt.InferenceSession("/content/logistic_regression.onnx")
knn_sess = rt.InferenceSession("/content/knn.onnx")

st.title("Machine Failure Risk Prediction API")

# User input
Temperature = st.number_input("Temperature", value=50.0)
Vibration = st.number_input("Vibration", value=0.5)
Power_Usage = st.number_input("Power Usage", value=200.0)
Humidity = st.number_input("Humidity", value=30.0)
Machine_Type = st.number_input("Machine Type", value=1.0)

input_data = np.array([[Temperature, Vibration, Power_Usage, Humidity, Machine_Type]], dtype=np.float32)

if st.button("Predict"):
    for name, sess in {
        "Decision Tree": dt_sess,
        "Logistic Regression": lr_sess,
        "KNN": knn_sess
    }.items():
        pred = sess.run(None, {"float_input": input_data})
        st.write(f"{name} Prediction: {pred[0][0]}")